baseurl = "https://condescending-hamilton-8de518.netlify.com/"
title = "Spencer Greenhalgh"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Spencer Greenhalgh"
    info = "Assistant Professor of Information Communication Technology"
    description = "Spencer Greenhalgh's personal website"
    keywords = "blog,personal"
    avatarurl = "images/SPG_2.jpeg"
    
    intro_para_1 = "My name is Spencer Greenhalgh, and I am an assistant professor of Information Communication Technology in the School of Information Science at the University of Kentucky. My background is in education—I earned a BA in French Teaching from Brigham Young University and a PhD in Educational Psychology and Educational Technology before joining the faculty at UK."
    
    intro_para_2 = "I focus my research on how digital technologies allow for the creation of both new kinds of learning (and other) communities and new kinds of research methods for studying those communities. The Internet is increasingly allowing learners to create social groups that challenge existing conceptions of how learning is organized. Furthermore, because these communities exist in digital spaces, they provide new methodological options for researchers."
    
    intro_para_3 = "For example, in much of my work, I have developed automated methods to collect data from Twitter hashtags used by teachers for professional learning and then identified the quantitative and qualitative methods best suited to understand these communities. These methods have allowed me to describe the ways in which these hashtag-based groups challenge the typical conceptions of what communities look like."

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 1
    url = "mailto:spencer.greenhalgh@uky.edu"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss fa-2x"
    weight = 2
    url = "/index.xml"
[[params.social]]
    name = "Google Scholar"
    icon = "fas fa-graduation-cap fa-2x"
    weight = 3
    url = "https://scholar.google.com/citations?user=o3JQjpcAAAAJ&hl=en&oi=ao"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 4
    url = "https://github.com/greenhas/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 5
    url = "https://twitter.com/spgreenhalgh/"
[[params.social]]
    name = "Micro.blog"
    icon = "fas fa-star fa-2x"
    weight = 6
    url = "https://micro.blog/spgreenhalgh/"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase fa-2x"
    weight = 3
    url = "https://keybase.io/spgreenhalgh"
[[params.social]]
    name = "Impodster Syndrome podcast"
    icon = "fas fa-podcast fa-2x"
    weight = 3
    url = "http://impodstersyndrome.libsyn.com/"


# Menu links

[[menu.main]]
    name = "CV"
    weight = 1
    url = "/cv.html"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"